apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: data-pod
  name: data-pod2
  namespace: web
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 3600
    image: busybox:1.28
    name: data-pod
    resources: {}
    volumeMounts:
    - name: temp-data
      mountPath: /tmp/data
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
  - name: temp-data
    persistentVolumeClaim:
      claimName: data-pvc
status: {}
