apiVersion: v1
kind: ConfigMap
metadata:
  name: fruit-service-ambassador-config
data:
  haproxy.cfg: |-
    global
        daemon
        maxconn 256

    defaults
        mode http
        timeout connect 5000ms
        tiemout client 50000ms
        tiemout server 50000ms

    listen http-in
        bind *:80
        server server1 127.0.0.1.8775 maxconn 32
